import type { Quote } from "../types";

/** 芸術・文学・音楽 */
export const ARTS: Quote[] = [
  {
    id: "shakespeare-1",
    origin: "en",
    en: "All the world's a stage, and all the men and women merely players.",
    ja: "この世は舞台、人はみな役者にすぎない。",
    kana: "このよはぶたい、ひとはみなやくしゃにすぎない。",
    author: "シェイクスピア",
    authorEn: "William Shakespeare",
    role: "劇作家",
    source: "『お気に召すまま』第2幕第7場",
    note: "人生を演劇にたとえ、人は生涯で七つの役を演じると続く有名な独白の冒頭。地位や役割は与えられた配役にすぎないという見方を示す。",
  },
  {
    id: "shakespeare-2",
    origin: "en",
    en: "To be, or not to be, that is the question.",
    ja: "生きるべきか、死ぬべきか、それが問題だ。",
    kana: "いきるべきか、しぬべきか、それがもんだいだ。",
    author: "シェイクスピア",
    authorEn: "William Shakespeare",
    role: "劇作家",
    source: "『ハムレット』第3幕第1場",
    note: "父を殺された王子ハムレットが、復讐と生死のあいだで揺れる独白の冒頭。英語圏で最も有名な一行とされる。",
  },
  {
    id: "vangogh-1",
    origin: "en",
    en: "Great things are not done by impulse, but by a series of small things brought together.",
    ja: "偉大なことは衝動ではなく、小さなことの積み重ねで成し遂げられる。",
    kana: "いだいなことはしょうどうではなく、ちいさなことのつみかさねでなしとげられる。",
    author: "ゴッホ",
    authorEn: "Vincent van Gogh",
    role: "画家",
    source: "弟テオへの手紙(1882)",
    note: "画家を志して間もない頃、思うように描けない苦しさの中で弟に宛てた手紙の一節。生前ほとんど売れなかったが、10年で2000点近い作品を残した。",
  },
  {
    id: "vangogh-2",
    origin: "en",
    en: "I dream my painting and I paint my dream.",
    ja: "私は絵を夢に見て、その夢を描く。",
    kana: "わたしはえをゆめにみて、そのゆめをえがく。",
    author: "ゴッホ",
    authorEn: "Vincent van Gogh",
    role: "画家",
    source: "ゴッホの言葉として広く伝わる",
    note: "見たままではなく、心に浮かんだ像を描くという制作態度。「星月夜」のうねる夜空のように、内面の情景がそのまま画面になっている。",
  },
  {
    id: "davinci-1",
    origin: "en",
    en: "Experience never errs; it is only your judgments that err.",
    ja: "経験は決して誤らない。誤るのは、我々の判断のほうだ。",
    kana: "けいけんはけっしてあやまらない。あやまるのは、われわれのはんだんのほうだ。",
    author: "レオナルド・ダ・ヴィンチ",
    authorEn: "Leonardo da Vinci",
    role: "芸術家・科学者",
    source: "『レオナルド・ダ・ヴィンチの手記』",
    note: "自然が示す事実は正しく、間違うのはそれを解釈する人間だという考え。解剖や観察のスケッチを大量に残した、徹底した観察主義の表れ。",
  },
  {
    id: "picasso-1",
    origin: "en",
    en: "Every child is an artist. The problem is how to remain an artist once we grow up.",
    ja: "子どもはみな芸術家だ。問題は大人になっても芸術家でいられるかだ。",
    kana: "こどもはみなげいじゅつかだ。もんだいはおとなになってもげいじゅつかでいられるかだ。",
    author: "パブロ・ピカソ",
    authorEn: "Pablo Picasso",
    role: "画家",
    source: "ピカソの言葉として広く伝わる",
    note: "子どもの持つ自由な表現力が、成長とともに常識に押し込められていくことへの指摘。ピカソ自身、写実を極めたのち意図的に子どもの絵のような形へ向かった。",
  },
  {
    id: "beethoven-1",
    origin: "en",
    en: "Music is a higher revelation than all wisdom and philosophy.",
    ja: "音楽は、あらゆる知恵や哲学よりも高き啓示である。",
    kana: "おんがくは、あらゆるちえやてつがくよりもたかきけいじである。",
    author: "ベートーヴェン",
    authorEn: "Ludwig van Beethoven",
    role: "作曲家",
    source: "ベッティーナ・フォン・アルニムが書き残した会話",
    note: "言葉や理屈では届かないものに音楽は届く、という確信。聴力を失いながら作曲を続けたベートーヴェンにとって、音楽は理性を超えた領域だった。",
  },
  {
    id: "mozart-1",
    origin: "en",
    en: "Neither a lofty degree of intelligence nor imagination nor both together go to the making of genius. Love, love, love, that is the soul of genius.",
    ja: "才能を作るのは知性でも想像力でもない。愛こそが天才の魂である。",
    kana: "さいのうをつくるのはちせいでもそうぞうりょくでもない。あいこそがてんさいのたましいである。",
    author: "モーツァルト",
    authorEn: "Wolfgang Amadeus Mozart",
    role: "作曲家",
    source: "モーツァルトの言葉として伝わる",
    note: "技術や頭のよさではなく、対象への愛情が創作を支えるという考え。幼少期から演奏旅行に明け暮れながら、生涯音楽への情熱を失わなかった。",
  },
  {
    id: "michelangelo-1",
    origin: "en",
    en: "I saw the angel in the marble and carved until I set him free.",
    ja: "大理石の中に天使が見えた。私はその天使を解き放つまで彫り続けた。",
    kana: "だいりせきのなかにてんしがみえた。わたしはそのてんしをときはなつまでほりつづけた。",
    author: "ミケランジェロ",
    authorEn: "Michelangelo",
    role: "彫刻家・画家",
    source: "ミケランジェロの言葉として広く伝わる",
    note: "彫刻とは石に形を与えるのではなく、すでに石の中にある形を掘り出す作業だという制作観。「ダビデ像」は他の彫刻家が見放した石材から生まれた。",
  },
  {
    id: "tolstoy-1",
    origin: "en",
    en: "Everyone thinks of changing the world, but no one thinks of changing himself.",
    ja: "誰もが世界を変えようと考えるが、自分を変えようとは考えない。",
    kana: "だれもがせかいをかえようとかんがえるが、じぶんをかえようとはかんがえない。",
    author: "トルストイ",
    authorEn: "Leo Tolstoy",
    role: "作家",
    source: "トルストイの言葉として広く伝わる",
    note: "社会批判は容易だが、自分の変革は難しいという皮肉。晩年のトルストイは貴族の地位や財産を手放し、自ら簡素な生活を実践しようとした。",
  },
  {
    id: "hugo-1",
    origin: "en",
    en: "Even the darkest night will end and the sun will rise.",
    ja: "どんなに暗い夜も必ず明け、太陽は昇る。",
    kana: "どんなにくらいよるもかならずあけ、たいようはのぼる。",
    author: "ヴィクトル・ユーゴー",
    authorEn: "Victor Hugo",
    role: "作家",
    source: "『レ・ミゼラブル』(1862)",
    note: "苦難は永遠には続かないという希望。囚人ジャン・バルジャンが赦しによって生き方を変える物語の中で語られる。",
  },
  {
    id: "wilde-1",
    origin: "en",
    en: "Be yourself; everyone else is already taken.",
    ja: "自分自身であれ。他の人はもう他の誰かで埋まっている。",
    kana: "じぶんじしんであれ。ほかのひとはもうほかのだれかでうまっている。",
    author: "オスカー・ワイルド",
    authorEn: "Oscar Wilde",
    role: "作家・劇作家",
    source: "ワイルドの言葉として広く伝わる",
    note: "誰かの真似をしても二番煎じにしかならない、という機知に富んだ言い回し。ワイルドは独自の服装や発言で当時の社会規範に挑み続けた。",
  },
  {
    id: "twain-1",
    origin: "en",
    en: "The secret of getting ahead is getting started.",
    ja: "前へ進む秘訣は、まず始めることである。",
    kana: "まえへすすむひけつは、まずはじめることである。",
    author: "マーク・トウェイン",
    authorEn: "Mark Twain",
    role: "作家",
    source: "トウェインの言葉として広く伝わる",
    note: "完璧な準備を待つより、着手することが前進の条件だという意味。大きな仕事も小さく分けて始めればよい、と続けて語られることが多い。",
  },
  {
    id: "twain-2",
    origin: "en",
    en: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    ja: "自分が多数派の側にいると気づいたら、立ち止まって考え直すときだ。",
    kana: "じぶんがたすうはのがわにいるときづいたら、たちどまってかんがえなおすときだ。",
    author: "マーク・トウェイン",
    authorEn: "Mark Twain",
    role: "作家",
    source: "『トウェインのノート』に伝わる",
    note: "多数であることは正しさの証明にならないという警句。奴隷制や帝国主義に対し、世論と異なる立場から批判を書き続けた作家らしい言葉。",
  },
];
