import type { Quote } from "../types";

/** 日本の偉人 */
export const JAPAN: Quote[] = [
  {
    id: "fukuzawa-1",
    origin: "ja",
    en: "Heaven creates no man above another, nor any man below another.",
    ja: "天は人の上に人を造らず、人の下に人を造らず。",
    kana: "てんはひとのうえにひとをつくらず、ひとのしたにひとをつくらず。",
    author: "福沢諭吉",
    authorEn: "Yukichi Fukuzawa",
    role: "思想家・教育者",
    source: "『学問のすゝめ』初編(1872)",
    note: "身分制度が解かれて間もない時期に、人は生まれながらに平等だと説いた冒頭の一節。ただし続けて、実際に差がつくのは学ぶか学ばないかだと書いている。",
  },
  {
    id: "fukuzawa-2",
    origin: "ja",
    en: "When you hit a wall, first change the way you see things.",
    ja: "行き詰まりは、その人の考え方が行き詰まっただけである。",
    kana: "ゆきづまりは、そのひとのかんがえかたがゆきづまっただけである。",
    author: "福沢諭吉",
    authorEn: "Yukichi Fukuzawa",
    role: "思想家・教育者",
    source: "福沢の言葉として伝わる",
    note: "状況そのものより、それを見る枠組みが固まってしまうことが問題だという指摘。西洋の学問を持ち込み、日本の常識を組み替えようとした人らしい視点。",
  },
  {
    id: "noguchi-1",
    origin: "ja",
    en: "I was not born into this world in vain.",
    ja: "私は無駄にこの世に生まれてきたのではない。",
    kana: "わたしはむだにこのよにうまれてきたのではない。",
    author: "野口英世",
    authorEn: "Hideyo Noguchi",
    role: "細菌学者",
    source: "野口の書簡に伝わる",
    note: "幼少期の大やけどで左手が不自由になり、貧しさの中から医学を志した人の言葉。黄熱病の研究のためアフリカに渡り、現地で自らも感染して亡くなった。",
  },
  {
    id: "matsushita-1",
    origin: "ja",
    en: "When you hit a wall, the first thing to change is your own point of view.",
    ja: "何事もゆきづまれば、まず自分のものの見方を変えることである。",
    kana: "なにごともゆきづまれば、まずじぶんのもののみかたをかえることである。",
    author: "松下幸之助",
    authorEn: "Konosuke Matsushita",
    role: "実業家",
    source: "松下の著作・講話に伝わる",
    note: "打つ手がないと感じたときこそ、前提を疑えという教え。小学校中退で丁稚奉公から身を起こし、松下電器を築いた経営者の実感がこもる。",
  },
  {
    id: "matsushita-2",
    origin: "ja",
    en: "Failure is not a failure if you keep going until you succeed.",
    ja: "成功するまで続ければ、失敗はない。",
    kana: "せいこうするまでつづければ、しっぱいはない。",
    author: "松下幸之助",
    authorEn: "Konosuke Matsushita",
    role: "実業家",
    source: "松下の著作・講話に伝わる",
    note: "途中でやめるから失敗になるのであって、続ける限りそれは過程にすぎないという考え方。景気の波を何度も越えてきた経営姿勢を表している。",
  },
  {
    id: "ryoma-1",
    origin: "ja",
    en: "Let the world say what it will; only I know what I must do.",
    ja: "世の中の人は何とも言わば言え。我が成すことは我のみぞ知る。",
    kana: "よのなかのひとはなんともいわばいえ。わがなすことはわれのみぞしる。",
    author: "坂本龍馬",
    authorEn: "Ryoma Sakamoto",
    role: "幕末の志士",
    source: "龍馬が詠んだ歌として伝わる",
    note: "周囲の批判に動じず自分の信じる道を行くという宣言。脱藩者という立場で薩長同盟を仲介した龍馬は、両陣営から疑われる立場にあった。",
  },
  {
    id: "ryoma-2",
    origin: "ja",
    en: "A man's worth is decided by what he does in the time he is given.",
    ja: "人間、志を立てるのに遅すぎるということはない。",
    kana: "にんげん、こころざしをたてるのにおそすぎるということはない。",
    author: "坂本龍馬",
    authorEn: "Ryoma Sakamoto",
    role: "幕末の志士",
    source: "龍馬の言葉として伝わる",
    note: "何かを始めるのに年齢は関係ないという励まし。龍馬自身、20代半ばで脱藩してから31歳で暗殺されるまでの数年間に日本の転換点を作った。",
  },
  {
    id: "yoshida-1",
    origin: "ja",
    en: "There has never been anyone who, with utter sincerity, failed to move others.",
    ja: "至誠にして動かざる者は、未だこれ有らざるなり。",
    kana: "しせいにしてうごかざるものは、いまだこれあらざるなり。",
    author: "吉田松陰",
    authorEn: "Shoin Yoshida",
    role: "思想家・教育者",
    source: "『孟子』の一節。松陰が座右の銘とした",
    note: "真心を尽くせば動かせない人はいない、という信念。松陰が主宰した松下村塾からは高杉晋作や伊藤博文らが育ち、明治維新の原動力となった。",
  },
  {
    id: "shibusawa-1",
    origin: "ja",
    en: "An abacus without morals, and morals without an abacus, both fail.",
    ja: "論語と算盤、どちらを欠いても正しい商いは成り立たない。",
    kana: "ろんごとそろばん、どちらをかいてもただしいあきないはなりたたない。",
    author: "渋沢栄一",
    authorEn: "Eiichi Shibusawa",
    role: "実業家",
    source: "『論語と算盤』(1916)",
    note: "道徳(論語)と利益(算盤)は両立するという主張。約500の企業設立に関わりながら財閥を作らなかった渋沢の、経済活動に対する基本姿勢を示す。",
  },
  {
    id: "hideyoshi-1",
    origin: "ja",
    en: "If a man does not act, nothing in this world will come to pass.",
    ja: "自ら動かねば、この世に成ることは何一つない。",
    kana: "みずからうごかねば、このよになることはなにひとつない。",
    author: "豊臣秀吉",
    authorEn: "Hideyoshi Toyotomi",
    role: "戦国武将",
    source: "秀吉の言葉として伝わる",
    note: "待っていても事は起こらないという行動主義。足軽から天下人まで上り詰めた出世は、機を見て自ら動き続けた結果だった。",
  },
  {
    id: "ieyasu-1",
    origin: "ja",
    en: "Life is like walking a long road with a heavy burden; do not be in a hurry.",
    ja: "人の一生は重荷を負うて遠き道を行くがごとし。急ぐべからず。",
    kana: "ひとのいっしょうはおもにをおうてとおきみちをゆくがごとし。いそぐべからず。",
    author: "徳川家康",
    authorEn: "Ieyasu Tokugawa",
    role: "武将・征夷大将軍",
    source: "「東照宮御遺訓」として伝わる(後世の作という説もある)",
    note: "人生は長丁場だから焦るなという戒め。人質として少年期を過ごし、信長・秀吉に仕えたのち60代で天下を取った家康の生涯と重ねて語られる。",
  },
  {
    id: "nobunaga-1",
    origin: "ja",
    en: "Do not be bound by precedent; the times themselves are always new.",
    ja: "前例にとらわれるな。時代は常に新しい。",
    kana: "ぜんれいにとらわれるな。じだいはつねにあたらしい。",
    author: "織田信長",
    authorEn: "Nobunaga Oda",
    role: "戦国武将",
    source: "信長の姿勢を表す言葉として伝わる",
    note: "鉄砲の大量運用や楽市楽座など、既存のやり方を壊して新しい仕組みを作った信長の行動原理を言い表したもの。",
  },
  {
    id: "murasaki-1",
    origin: "ja",
    en: "People's hearts are as varied as their faces.",
    ja: "人の心は顔かたちと同じく、それぞれに異なるものだ。",
    kana: "ひとのこころはかおかたちとおなじく、それぞれにことなるものだ。",
    author: "紫式部",
    authorEn: "Murasaki Shikibu",
    role: "作家・歌人",
    source: "『源氏物語』の趣旨をまとめた言い方",
    note: "人の内面は一様ではないという観察。多数の登場人物それぞれに異なる心理を書き分けた『源氏物語』の作り方そのものを表している。",
  },
  {
    id: "basho-1",
    origin: "ja",
    en: "Do not follow in the footsteps of the old masters; seek what they sought.",
    ja: "古人の跡を求めず、古人の求めたる所を求めよ。",
    kana: "こじんのあとをもとめず、こじんのもとめたるところをもとめよ。",
    author: "松尾芭蕉",
    authorEn: "Matsuo Basho",
    role: "俳人",
    source: "『許六離別詞』(柴門の辞)",
    note: "先人の作品を真似るのではなく、先人が目指したものを自分も目指せという教え。弟子の許六との別れに際して贈られた言葉。",
  },
  {
    id: "tsuda-1",
    origin: "ja",
    en: "What matters is not knowledge itself, but the character that puts it to use.",
    ja: "大切なのは知識そのものではなく、それを生かす人格である。",
    kana: "たいせつなのはちしきそのものではなく、それをいかすじんかくである。",
    author: "津田梅子",
    authorEn: "Umeko Tsuda",
    role: "教育者",
    source: "津田の教育理念を表す言葉として伝わる",
    note: "6歳で岩倉使節団に随行して渡米し、帰国後に女子英学塾(現・津田塾大学)を創設。知識の詰め込みではなく人格を育てる教育を掲げた。",
  },
  {
    id: "hokusai-1",
    origin: "ja",
    en: "At seventy-three I finally grasped a little of the true form of things.",
    ja: "七十三歳にして、ようやく物の形の真を少し悟った。",
    kana: "しちじゅうさんさいにして、ようやくもののかたちのしんをすこしさとった。",
    author: "葛飾北斎",
    authorEn: "Katsushika Hokusai",
    role: "浮世絵師",
    source: "『富嶽百景』跋文(1834)",
    note: "70歳を超えてなお発展途上だと書いた一節。続けて「百歳を超えれば一点一画が生きたものになるだろう」と述べ、生涯上達を求め続けた。",
  },
  {
    id: "uesugi-1",
    origin: "ja",
    en: "If you act, it is done; if you do not, it is not.",
    ja: "為せば成る、為さねば成らぬ何事も。",
    kana: "なせばなる、なさねばならぬなにごとも。",
    author: "上杉鷹山",
    authorEn: "Yozan Uesugi",
    role: "米沢藩主",
    source: "鷹山が家臣に与えた歌として伝わる",
    note: "続きは「成らぬは人の為さぬなりけり」。財政破綻寸前だった米沢藩を、倹約と殖産興業で立て直した藩主が、家臣を励ますために詠んだ。",
  },
  {
    id: "saigo-1",
    origin: "ja",
    en: "Revere heaven, love people.",
    ja: "天を敬い、人を愛す。",
    kana: "てんをうやまい、ひとをあいす。",
    author: "西郷隆盛",
    authorEn: "Takamori Saigo",
    role: "武士・政治家",
    source: "「敬天愛人」として伝わる西郷の座右の銘",
    note: "天の道理に従い、人を大切にせよという生き方。私利私欲を退けたこの姿勢が、多くの人を惹きつけて明治維新の推進力になった。",
  },
  {
    id: "sen-1",
    origin: "ja",
    en: "Each meeting is a once-in-a-lifetime encounter.",
    ja: "一期一会、この出会いは二度と繰り返されない。",
    kana: "いちごいちえ、このであいはにどとくりかえされない。",
    author: "千利休",
    authorEn: "Sen no Rikyu",
    role: "茶人",
    source: "利休の教えとして伝わり、のちに井伊直弼が言葉にまとめた",
    note: "同じ顔ぶれで同じ茶会を開いても、その一席は二度と再現できない。だからこの一度に心を尽くせという、茶の湯の根本にある考え方。",
  },
  {
    id: "hideyo-2",
    origin: "ja",
    en: "Endurance is bitter, but its fruit is sweet.",
    ja: "忍耐は苦い。しかしその実は甘い。",
    kana: "にんたいはにがい。しかしそのみはあまい。",
    author: "野口英世",
    authorEn: "Hideyo Noguchi",
    role: "細菌学者",
    source: "野口が好んで引用した言葉として伝わる",
    note: "苦しい時期を耐えた先に成果があるという意味。渡米後、無給に近い立場から研究を始め、数年で国際的な評価を得るまでになった。",
  },
];
