import type { Quote } from "../types";

/**
 * 現代の実業家・クリエイターの言葉。
 *
 * 出典はいずれも本人のYouTubeチャンネルでの発言。歴史上の偉人と違って
 * 書物に残っているわけではないので、`source` にはどの動画・どの場面かを書いている。
 */
export const MODERN: Quote[] = [
  {
    id: "hikaru-1",
    origin: "ja",
    en: "I want to keep feeling excited until the day I die.",
    ja: "死ぬまでワクワクしたい。",
    kana: "しぬまでわくわくしたい。",
    author: "ヒカル",
    authorEn: "Hikaru",
    role: "YouTuber・実業家",
    source: "YouTube「10億円で買ったホテルを完全公開します」",
    note: "宮古島の10億円のホテルを、実物を見ずに直感とデータだけで購入すると決めたときの言葉。安定や保守に走らず、予測のつかない事態にこそ心を躍らせるという姿勢。",
  },
  {
    id: "hikaru-2",
    origin: "ja",
    en: "My value is at its lowest price right now.",
    ja: "俺の価値は今が最安値。",
    kana: "おれのかちはいまがさいやすね。",
    author: "ヒカル",
    authorEn: "Hikaru",
    role: "YouTuber・実業家",
    source: "YouTube「10億円で買ったホテルを完全公開します」",
    note: "今の自分は通過点にすぎず、この先もっと価値が上がっていくという確信を、株価にたとえて言い切った言葉。自己肯定感の強さがそのまま表れている。",
  },
  {
    id: "hikaru-3",
    origin: "ja",
    en: "The flexibility to take back what you said matters.",
    ja: "前言撤回できる柔軟性が大事。",
    kana: "ぜんげんてっかいできるじゅうなんせいがだいじ。",
    author: "ヒカル",
    authorEn: "Hikaru",
    role: "YouTuber・実業家",
    source: "YouTube「10億円のホテルの次は4億円のヴィラを買いました」",
    note: "過去の栄光に固執して衰退していく人との違いを語った場面の言葉。続けて「ダメだと思っていることをやりきるほうがナンセンス」と述べ、失敗を認めて即座に軌道修正する重要性を説いている。",
  },
  {
    id: "hikaru-4",
    origin: "ja",
    en: "Only those who set out to become something ever become it.",
    ja: "なりたいものになれるのは、なろうとしたものだけ。",
    kana: "なりたいものになれるのは、なろうとしたものだけ。",
    author: "ヒカル",
    authorEn: "Hikaru",
    role: "YouTuber・実業家",
    source: "YouTube「10億円で買ったホテルを完全公開します」",
    note: "「王になる」という自身の大きな目標を本気で語った場面での言葉。夢は願うだけでは届かず、志して行動に移した者だけが手にできるという信念。",
  },
  {
    id: "hikaru-5",
    origin: "ja",
    en: "What moves your life is not money. It is your own awareness.",
    ja: "人生を動かすのはお金じゃない。意識なんだよ、自分自身の。",
    kana: "じんせいをうごかすのはおかねじゃない。いしきなんだよ、じぶんじしんの。",
    author: "ヒカル",
    authorEn: "Hikaru",
    role: "YouTuber・実業家",
    source: "YouTube「なぜヒカルのシャンプーは爆発的に売れたのか？」",
    note: "視聴者に向けてマインドセットの重要性を説いた場面。持っている金額や環境よりも、物事の捉え方が変わった瞬間に人生は動き出すという考え方。",
  },
  {
    id: "hikaru-6",
    origin: "ja",
    en: "Right now is the youngest and earliest you will ever be.",
    ja: "今が一番若くて早い。いつ始めるのかってこと。",
    kana: "いまがいちばんわかくてはやい。いつはじめるのかってこと。",
    author: "ヒカル",
    authorEn: "Hikaru",
    role: "YouTuber・実業家",
    source: "YouTube「大切な人たちと35歳の誕生日を過ごしました」",
    note: "年齢を理由に成長を諦めないでほしいと視聴者に語りかけた言葉。過去には戻れない以上、着手するなら常に今が最速だという考え。",
  },
  {
    id: "hikaru-7",
    origin: "ja",
    en: "Those who fear losing something can never gain anything.",
    ja: "失うことを恐れてる人間は、何かを得ることができない。",
    kana: "うしなうことをおそれてるにんげんは、なにかをえることができない。",
    author: "ヒカル",
    authorEn: "Hikaru",
    role: "YouTuber・実業家",
    source: "YouTube「ヒカル（Hikaru）」チャンネル",
    note: "リスクを懸念して慎重な意見を述べる仲間に対し、変化を恐れる姿勢を厳しく指摘した場面。現状維持は衰退であり、大きな成功には捨てる覚悟が要るという考え。",
  },
  {
    id: "hikaru-8",
    origin: "ja",
    en: "It continues not by my willpower, but by the system I built.",
    ja: "僕の意思で続くんじゃなくて、仕組みで続きます。",
    kana: "ぼくのいしでつづくんじゃなくて、しくみでつづきます。",
    author: "ヒカル",
    authorEn: "Hikaru",
    role: "YouTuber・実業家",
    source: "YouTube「プライベートジェットで石垣島に行き本田圭佑さんに会いました」",
    note: "朝活が続かないのではと疑問視されたときの返答。「朝、俺を起こす人間が3人いる」と続く。継続は気合ではなく、やらざるを得ない環境を作れるかで決まるという考え方。",
  },
  {
    id: "hikaru-9",
    origin: "ja",
    en: "Taking command of your first hour changes your whole life.",
    ja: "最初の一時間を自分が支配することで、人生が変わっていく。",
    kana: "さいしょのいちじかんをじぶんがしはいすることで、じんせいがかわっていく。",
    author: "ヒカル",
    authorEn: "Hikaru",
    role: "YouTuber・実業家",
    source: "YouTube「大切な人たちと35歳の誕生日を過ごしました」",
    note: "朝のルーティンの重要性を視聴者に説いた場面。一日の始まりに自分で決めた行動を置くと、良い習慣が連鎖して一日全体の質が上がるという時間管理の考え方。",
  },
  {
    id: "hikaru-10",
    origin: "ja",
    en: "Impossibility does not exist; you just decided it was impossible.",
    ja: "世の中に不可能という実態はなくて、勝手に自分で無理だと思ってるだけ。",
    kana: "よのなかにふかのうというじったいはなくて、かってにじぶんでむりだとおもってるだけ。",
    author: "ヒカル",
    authorEn: "Hikaru",
    role: "YouTuber・実業家",
    source: "YouTube「なぜヒカルのシャンプーは爆発的に売れたのか？」",
    note: "ビジネスパートナーを鼓舞しながら、限界を決めずに挑戦し続ける姿勢を説いた場面。限界は客観的な事実ではなく主観にすぎないという見方。",
  },
];
