import type { Quote } from "../types";

/** 哲学・思想 */
export const PHILOSOPHY: Quote[] = [
  {
    id: "socrates-1",
    origin: "en",
    en: "The unexamined life is not worth living.",
    ja: "吟味されざる生に、生きる値打ちなし。",
    kana: "ぎんみされざるせいに、いきるねうちなし。",
    author: "ソクラテス",
    authorEn: "Socrates",
    role: "哲学者",
    source: "プラトン『ソクラテスの弁明』38a",
    note: "自分の生き方を問い直さないまま過ごす人生には価値がない、という主張。死刑判決を受けた法廷で、哲学をやめれば助かると言われた際にこう答えたと伝えられる。",
  },
  {
    id: "socrates-2",
    origin: "en",
    en: "I know that I know nothing.",
    ja: "私は、自分が何も知らないということを知っている。",
    kana: "わたしは、じぶんがなにもしらないということをしっている。",
    author: "ソクラテス",
    authorEn: "Socrates",
    role: "哲学者",
    source: "『ソクラテスの弁明』の趣旨をまとめた言い方として広く伝わる",
    note: "「無知の知」と呼ばれる考え方。知らないことを自覚している分だけ、知ったつもりでいる人より賢い、という逆説で、そこから学びが始まるとした。",
  },
  {
    id: "aristotle-1",
    origin: "en",
    en: "Man is by nature a political animal.",
    ja: "人間は、その本性において社会的な動物である。",
    kana: "にんげんは、そのほんせいにおいてしゃかいてきなどうぶつである。",
    author: "アリストテレス",
    authorEn: "Aristotle",
    role: "哲学者",
    source: "『政治学』第1巻",
    note: "人は一人では生きられず、共同体の中でこそ人間らしくなれるという考え。この一文が、その後の政治哲学の出発点になった。",
  },
  {
    id: "aristotle-2",
    origin: "en",
    en: "Happiness depends upon ourselves.",
    ja: "幸福は、自分自身にかかっている。",
    kana: "こうふくは、じぶんじしんにかかっている。",
    author: "アリストテレス",
    authorEn: "Aristotle",
    role: "哲学者",
    source: "『ニコマコス倫理学』の趣旨をまとめた言い方",
    note: "幸福は運や他人から与えられるものではなく、自分がどう生きるかで決まるという立場。よい習慣を積み重ねることが幸福につながるとアリストテレスは説いた。",
  },
  {
    id: "confucius-1",
    origin: "ja",
    en: "To know what you know and to know what you do not know: that is knowledge.",
    ja: "知るを知るとなし、知らざるを知らずとなす。これ知るなり。",
    kana: "しるをしるとなし、しらざるをしらずとなす。これしるなり。",
    author: "孔子",
    authorEn: "Confucius",
    role: "思想家",
    source: "『論語』為政篇",
    note: "知っていることと知らないことの線引きができている状態こそが「知る」ということだ、という教え。弟子の子路に対して語られた言葉とされる。",
  },
  {
    id: "confucius-2",
    origin: "ja",
    en: "Do not impose on others what you do not wish for yourself.",
    ja: "己の欲せざる所、人に施すこと勿れ。",
    kana: "おのれのほっせざるところ、ひとにほどこすことなかれ。",
    author: "孔子",
    authorEn: "Confucius",
    role: "思想家",
    source: "『論語』衛霊公篇",
    note: "自分がされたくないことは人にもするな、という教え。弟子から「一生涯行うべき一言は」と問われ、孔子が「恕(思いやり)」として答えたもの。",
  },
  {
    id: "confucius-3",
    origin: "ja",
    en: "Is it not a pleasure to learn and to practice what you have learned?",
    ja: "学びて時にこれを習う、また喜ばしからずや。",
    kana: "まなびてときにこれをならう、またよろこばしからずや。",
    author: "孔子",
    authorEn: "Confucius",
    role: "思想家",
    source: "『論語』学而篇の冒頭",
    note: "学んだことを折にふれて繰り返し身につけていくのは、なんと喜ばしいことか、という意味。『論語』全体の一番はじめに置かれた、学びを肯定する言葉。",
  },
  {
    id: "seneca-1",
    origin: "en",
    en: "It is not that we have a short time to live, but that we waste a lot of it.",
    ja: "人生が短いのではない。我々がそれを浪費しているのだ。",
    kana: "じんせいがみじかいのではない。われわれがそれをろうひしているのだ。",
    author: "セネカ",
    authorEn: "Seneca",
    role: "哲学者",
    source: "『人生の短さについて』(紀元1世紀)",
    note: "時間が足りないのではなく使い方が悪いのだという指摘。他人の用事や見栄に時間を明け渡している人ほど「忙しい」と言う、とセネカは書いている。",
  },
  {
    id: "marcus-1",
    origin: "en",
    en: "You have power over your mind, not outside events. Realize this, and you will find strength.",
    ja: "自分の心は思い通りになるが、外の出来事はそうではない。そう悟れば力が湧く。",
    kana: "じぶんのこころはおもいどおりになるが、そとのできごとはそうではない。そうさとればちからがわく。",
    author: "マルクス・アウレリウス",
    authorEn: "Marcus Aurelius",
    role: "ローマ皇帝・哲学者",
    source: "『自省録』",
    note: "変えられるものと変えられないものを見分けよ、というストア派の中心的な考え。疫病と戦争に追われた皇帝が、陣中で自分に言い聞かせるために書き留めた。",
  },
  {
    id: "nietzsche-1",
    origin: "en",
    en: "He who has a why to live can bear almost any how.",
    ja: "なぜ生きるかを知る者は、ほとんどあらゆる生き方に耐える。",
    kana: "なぜいきるかをしるものは、ほとんどあらゆるいきかたにたえる。",
    author: "ニーチェ",
    authorEn: "Friedrich Nietzsche",
    role: "哲学者",
    source: "『偶像の黄昏』(1888)「箴言と矢」",
    note: "目的さえ持てれば、どんな苦しい状況にも耐えられるという意味。のちに心理学者フランクルが強制収容所の体験を語る際に引用し、広く知られるようになった。",
  },
  {
    id: "goethe-1",
    origin: "en",
    en: "Knowing is not enough; we must apply.",
    ja: "知るだけでは足りない。それを使わなければならない。",
    kana: "しるだけではたりない。それをつかわなければならない。",
    author: "ゲーテ",
    authorEn: "Johann Wolfgang von Goethe",
    role: "詩人・作家",
    source: "『ヴィルヘルム・マイスターの遍歴時代』",
    note: "知識は実行に移して初めて意味を持つという考え。ゲーテは詩人であると同時に、鉱山経営や色彩の研究にも携わった実務家でもあった。",
  },
  {
    id: "kant-1",
    origin: "en",
    en: "Have the courage to use your own understanding.",
    ja: "自分自身の理性を使う勇気を持て。",
    kana: "じぶんじしんのりせいをつかうゆうきをもて。",
    author: "カント",
    authorEn: "Immanuel Kant",
    role: "哲学者",
    source: "『啓蒙とは何か』(1784)",
    note: "他人の指示や慣習に頼らず、自分の頭で考えよという呼びかけ。カントはこれを啓蒙の標語とし、人が「未成年状態」から抜け出すことだと説明した。",
  },
  {
    id: "laotzu-1",
    origin: "ja",
    en: "A journey of a thousand miles begins with a single step.",
    ja: "千里の道も一歩から始まる。",
    kana: "せんりのみちもいっぽからはじまる。",
    author: "老子",
    authorEn: "Lao Tzu",
    role: "思想家",
    source: "『老子』第64章",
    note: "どれほど大きな事業も、最初の小さな一歩から始まるという教え。原文は「千里の行も足下より始まる」で、大事は小事の積み重ねだと説く文脈にある。",
  },
  {
    id: "laotzu-2",
    origin: "ja",
    en: "He who knows others is wise; he who knows himself is enlightened.",
    ja: "人を知る者は智なり、自らを知る者は明なり。",
    kana: "ひとをしるものはちなり、みずからをしるものはめいなり。",
    author: "老子",
    authorEn: "Lao Tzu",
    role: "思想家",
    source: "『老子』第33章",
    note: "他人を見抜くのは賢さだが、自分自身を見抜くのはそれ以上に深い明るさだという対比。外へ向かう知よりも、内へ向かう洞察を上に置いている。",
  },
  {
    id: "buddha-1",
    origin: "ja",
    en: "What we think, we become.",
    ja: "人は、その心が思い描いたとおりのものになる。",
    kana: "ひとは、そのこころがおもいえがいたとおりのものになる。",
    author: "ブッダ",
    authorEn: "Buddha",
    role: "宗教家",
    source: "『法句経(ダンマパダ)』冒頭の趣旨として広く伝わる",
    note: "行いも人生も、まず心のあり方から始まるという教え。『法句経』は「心がすべてに先立ち、心がすべてを作る」という一節から始まる。",
  },
  {
    id: "descartes-1",
    origin: "en",
    en: "I think, therefore I am.",
    ja: "我思う、ゆえに我あり。",
    kana: "われおもう、ゆえにわれあり。",
    author: "デカルト",
    authorEn: "Rene Descartes",
    role: "哲学者・数学者",
    source: "『方法序説』(1637)",
    note: "すべてを疑ってみても、疑っている自分の存在だけは疑えない、という結論。ここを出発点にして確実な知識を組み立て直そうとした、近代哲学の起点となる一文。",
  },
  {
    id: "aurelius-2",
    origin: "en",
    en: "The happiness of your life depends upon the quality of your thoughts.",
    ja: "人生の幸福は、思考の質によって決まる。",
    kana: "じんせいのこうふくは、しこうのしつによってきまる。",
    author: "マルクス・アウレリウス",
    authorEn: "Marcus Aurelius",
    role: "ローマ皇帝・哲学者",
    source: "『自省録』の趣旨をまとめた言い方",
    note: "同じ出来事でも、それをどう受け取るかで幸不幸は変わるという考え。ストア派は「出来事そのもの」と「それについての判断」を切り分けることを重視した。",
  },
  {
    id: "epictetus-1",
    origin: "en",
    en: "It is not what happens to you, but how you react to it that matters.",
    ja: "重要なのは何が起きたかではなく、それにどう反応するかだ。",
    kana: "じゅうようなのはなにがおきたかではなく、それにどうはんのうするかだ。",
    author: "エピクテトス",
    authorEn: "Epictetus",
    role: "哲学者",
    source: "エピクテトスの言葉として広く伝わる",
    note: "出来事は選べないが、それへの態度は自分で選べるという考え。エピクテトス自身が奴隷の身分から解放されて哲学者になった経歴を持つ。",
  },
];
