import type { Quote } from "../types";

/** 科学・発明 */
export const SCIENCE: Quote[] = [
  {
    id: "edison-1",
    origin: "en",
    en: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    ja: "天才とは、一％のひらめきと九十九％の汗である。",
    kana: "てんさいとは、いちぱーせんとのひらめきときゅうじゅうきゅうぱーせんとのあせである。",
    author: "トーマス・エジソン",
    authorEn: "Thomas Edison",
    role: "発明家",
    source: "1900年前後の談話として各紙に伝わる",
    note: "才能そのものより、地道な試行の積み重ねこそが発明を生むという意味。エジソンは電球のフィラメント材料を探すのに数千種類を試したと言われ、この言葉はその実感から出ている。",
  },
  {
    id: "edison-2",
    origin: "en",
    en: "I have not failed. I've just found ten thousand ways that won't work.",
    ja: "私は失敗していない。うまくいかない方法を一万通り見つけただけだ。",
    kana: "わたしはしっぱいしていない。うまくいかないほうほうをいちまんとおりみつけただけだ。",
    author: "トーマス・エジソン",
    authorEn: "Thomas Edison",
    role: "発明家",
    source: "伝記に伝わる言葉",
    note: "うまくいかなかった実験も「使えない方法が一つ確定した」という前進だという捉え方。失敗をデータとみなす姿勢が、膨大な試行を続ける原動力になった。",
  },
  {
    id: "einstein-1",
    origin: "en",
    en: "Imagination is more important than knowledge.",
    ja: "想像力は知識よりも大切である。",
    kana: "そうぞうりょくはちしきよりもたいせつである。",
    author: "アルベルト・アインシュタイン",
    authorEn: "Albert Einstein",
    role: "物理学者",
    source: "1929年『サタデー・イブニング・ポスト』誌のインタビュー",
    note: "知識はすでに分かっていることの範囲にとどまるが、想像力はその先へ手を伸ばせる、という考え。相対性理論も「光と一緒に走ったらどう見えるか」という空想から出発している。",
  },
  {
    id: "einstein-2",
    origin: "en",
    en: "Try not to become a man of success, but rather try to become a man of value.",
    ja: "成功者になろうとするな。むしろ価値のある人間になろうとせよ。",
    kana: "せいこうしゃになろうとするな。むしろかちのあるにんげんになろうとせよ。",
    author: "アルベルト・アインシュタイン",
    authorEn: "Albert Einstein",
    role: "物理学者",
    source: "1955年『LIFE』誌に載った知人の回想",
    note: "成功は他人からの評価だが、価値は自分が世界に何を与えたかで決まる、という対比。晩年、名声に囲まれたアインシュタインが若者に向けて語ったとされる。",
  },
  {
    id: "curie-1",
    origin: "en",
    en: "Nothing in life is to be feared, it is only to be understood.",
    ja: "人生において恐れるべきものは何もない。ただ理解すべきものがあるだけだ。",
    kana: "じんせいにおいておそれるべきものはなにもない。ただりかいすべきものがあるだけだ。",
    author: "マリー・キュリー",
    authorEn: "Marie Curie",
    role: "物理学者・化学者",
    source: "娘エーヴ・キュリーによる伝記に伝わる",
    note: "恐れは正体が分からないことから生まれるので、理解すれば恐れる必要はなくなるという意味。当時未知だった放射線に生涯向き合い続けた本人の姿勢がそのまま表れている。",
  },
  {
    id: "newton-1",
    origin: "en",
    en: "If I have seen further, it is by standing on the shoulders of giants.",
    ja: "私が遠くを見渡せたのは、巨人の肩の上に立っていたからだ。",
    kana: "わたしがとおくをみわたせたのは、きょじんのかたのうえにたっていたからだ。",
    author: "アイザック・ニュートン",
    authorEn: "Isaac Newton",
    role: "物理学者・数学者",
    source: "1675年、ロバート・フックへ宛てた手紙",
    note: "自分の発見は先人たちの積み重ねの上にあるという謙遜。ガリレオやケプラーの研究があってこそ万有引力にたどり着けた、という科学の継承性を言い表している。",
  },
  {
    id: "darwin-1",
    origin: "en",
    en: "Ignorance more frequently begets confidence than does knowledge.",
    ja: "無知はしばしば、知識よりも自信を生む。",
    kana: "むちはしばしば、ちしきよりもじしんをうむ。",
    author: "チャールズ・ダーウィン",
    authorEn: "Charles Darwin",
    role: "自然科学者",
    source: "『人間の由来』(1871) 序論",
    note: "知らない人ほど断言し、深く知る人ほど慎重になるという指摘。進化論が激しい論争にさらされる中で、確信をもって否定してくる人々を前に書かれた一文。",
  },
  {
    id: "galileo-1",
    origin: "en",
    en: "You cannot teach a man anything; you can only help him find it within himself.",
    ja: "人に何かを教えることはできない。自ら気づく手助けができるだけだ。",
    kana: "ひとになにかをおしえることはできない。みずからきづくてだすけができるだけだ。",
    author: "ガリレオ・ガリレイ",
    authorEn: "Galileo Galilei",
    role: "天文学者・物理学者",
    source: "ガリレオの言葉として広く伝わる",
    note: "学びとは外から詰め込むものではなく、本人の中で起こるものだという教育観。自分の目で望遠鏡をのぞかせ、事実を確かめさせようとしたガリレオらしい言葉。",
  },
  {
    id: "pasteur-1",
    origin: "en",
    en: "In the fields of observation, chance favors only the prepared mind.",
    ja: "観察の領域において、偶然は準備された心にのみ味方する。",
    kana: "かんさつのりょういきにおいて、ぐうぜんはじゅんびされたこころにのみみかたする。",
    author: "ルイ・パスツール",
    authorEn: "Louis Pasteur",
    role: "細菌学者",
    source: "1854年、リール大学での講演",
    note: "幸運な発見は誰にでも起こりうるが、それを見逃さず意味を掴めるのは備えのある人だけ、という意味。偶然生えたカビから抗生物質が生まれた歴史がこれを裏づけている。",
  },
  {
    id: "tesla-1",
    origin: "en",
    en: "The present is theirs; the future, for which I really worked, is mine.",
    ja: "現在は彼らのものだ。私が本当に力を注いだ未来は、私のものだ。",
    kana: "げんざいはかれらのものだ。わたしがほんとうにちからをそそいだみらいは、わたしのものだ。",
    author: "ニコラ・テスラ",
    authorEn: "Nikola Tesla",
    role: "発明家・電気技術者",
    source: "テスラの言葉として伝わる",
    note: "同時代に評価されなくとも、未来がそれを証明するという確信。交流送電や無線技術は当時理解されにくかったが、現代の電力網はまさに彼の構想の上に立っている。",
  },
  {
    id: "hawking-1",
    origin: "en",
    en: "Intelligence is the ability to adapt to change.",
    ja: "知性とは、変化に適応する能力のことである。",
    kana: "ちせいとは、へんかにてきおうするのうりょくのことである。",
    author: "スティーヴン・ホーキング",
    authorEn: "Stephen Hawking",
    role: "理論物理学者",
    source: "ホーキングの言葉として広く伝わる",
    note: "知性を「知識の量」ではなく「変化への対応力」と定義した言葉。難病で身体の自由を失いながら、その都度新しい方法を見つけて研究を続けた本人の生き方と重なる。",
  },
  {
    id: "hawking-2",
    origin: "en",
    en: "However difficult life may seem, there is always something you can do.",
    ja: "人生がどんなに困難に見えても、必ずできることがある。",
    kana: "じんせいがどんなにこんなんにみえても、かならずできることがある。",
    author: "スティーヴン・ホーキング",
    authorEn: "Stephen Hawking",
    role: "理論物理学者",
    source: "2010年代の講演・インタビューで繰り返し語った言葉",
    note: "21歳でALSと診断され余命数年と告げられながら、その後半世紀にわたり研究を続けた人の言葉。できないことを数えるより、できることを探せという励まし。",
  },
  {
    id: "ford-1",
    origin: "en",
    en: "Whether you think you can, or you think you can't, you're right.",
    ja: "できると思うか、できないと思うか。どちらも正しい。",
    kana: "できるとおもうか、できないとおもうか。どちらもただしい。",
    author: "ヘンリー・フォード",
    authorEn: "Henry Ford",
    role: "実業家",
    source: "フォードの言葉として広く伝わる",
    note: "できないと思えばやらないので本当にできず、できると思えば手を動かすので実現する。思い込みが結果を決めてしまうという指摘。",
  },
  {
    id: "ford-2",
    origin: "en",
    en: "Coming together is a beginning; keeping together is progress; working together is success.",
    ja: "集まることは始まり、続けることは進歩、共に働くことが成功である。",
    kana: "あつまることははじまり、つづけることはしんぽ、ともにはたらくことがせいこうである。",
    author: "ヘンリー・フォード",
    authorEn: "Henry Ford",
    role: "実業家",
    source: "フォードの言葉として広く伝わる",
    note: "チームは人が集まっただけでは機能せず、続けて初めて力になるという段階論。流れ作業による大量生産は、多くの人の連携で成り立っていた。",
  },
  {
    id: "wright-1",
    origin: "en",
    en: "If we all worked on the assumption that what is accepted as true is really true, there would be little hope of advance.",
    ja: "正しいとされることを疑わずにいたら、進歩の望みはほとんどない。",
    kana: "ただしいとされることをうたがわずにいたら、しんぽののぞみはほとんどない。",
    author: "オーヴィル・ライト",
    authorEn: "Orville Wright",
    role: "飛行機の発明者",
    source: "ライト兄弟の言葉として伝わる",
    note: "「人間は空を飛べない」が常識だった時代に、その前提そのものを疑って初の動力飛行を成功させた兄弟の言葉。常識を検証し直すことが発明の出発点になる。",
  },
  {
    id: "franklin-1",
    origin: "en",
    en: "Lost time is never found again.",
    ja: "失われた時間は、二度と取り戻せない。",
    kana: "うしなわれたじかんは、にどともどせない。",
    author: "ベンジャミン・フランクリン",
    authorEn: "Benjamin Franklin",
    role: "政治家・科学者",
    source: "『貧しいリチャードの暦』(1748)",
    note: "お金は稼ぎ直せるが時間は戻らない、という時間の不可逆性への戒め。印刷業・科学・政治を並行してこなしたフランクリンは、時間の使い方を徹底して管理していた。",
  },
  {
    id: "franklin-2",
    origin: "en",
    en: "Well done is better than well said.",
    ja: "うまく言うことより、うまく行うこと。",
    kana: "うまくいうことより、うまくおこなうこと。",
    author: "ベンジャミン・フランクリン",
    authorEn: "Benjamin Franklin",
    role: "政治家・科学者",
    source: "『貧しいリチャードの暦』(1737)",
    note: "立派なことを語るより、実際にやってみせるほうが価値があるという実践主義。避雷針の発明も、理論を語るだけでなく自ら凧を揚げて確かめたことから生まれた。",
  },
  {
    id: "nightingale-1",
    origin: "en",
    en: "I attribute my success to this: I never gave or took any excuse.",
    ja: "私の成功の理由はこれだ。言い訳をせず、言い訳を受け入れもしなかった。",
    kana: "わたしのせいこうのりゆうはこれだ。いいわけをせず、いいわけをうけいれもしなかった。",
    author: "フローレンス・ナイチンゲール",
    authorEn: "Florence Nightingale",
    role: "看護師・統計学者",
    source: "ナイチンゲールの言葉として伝わる",
    note: "クリミア戦争の野戦病院で、資材不足を理由にせず衛生環境を作り変えた姿勢。死亡率の原因を統計で示して軍を動かした、徹底した現実主義がうかがえる。",
  },
];
