import type { Quote } from "../types";

/**
 * 短くて打ちやすい名言。
 * 読みが概ね20字前後に収まるものを集めてある(初心者や短時間で遊ぶとき向け)。
 */
export const SHORT: Quote[] = [
  {
    id: "s-caesar-1",
    origin: "en",
    en: "I came, I saw, I conquered.",
    ja: "来た、見た、勝った。",
    kana: "きた、みた、かった。",
    author: "ユリウス・カエサル",
    authorEn: "Julius Caesar",
    role: "古代ローマの政治家",
    source: "紀元前47年、ゼラの戦いの戦勝報告",
    note: "ポントス王を破った際、元老院に送った報告がこの三語だけだったと伝わる。短さそのものが、戦いの圧倒的な速さを物語る演出になっている。",
  },
  {
    id: "s-nietzsche-2",
    origin: "en",
    en: "What does not kill me makes me stronger.",
    ja: "私を殺さないものは、私を強くする。",
    kana: "わたしをころさないものは、わたしをつよくする。",
    author: "ニーチェ",
    authorEn: "Friedrich Nietzsche",
    role: "哲学者",
    source: "『偶像の黄昏』(1888)「箴言と矢」",
    note: "苦難を乗り越えた経験が人を鍛えるという意味。ニーチェ自身、激しい頭痛と眼病に苦しみながら大学教授職を辞して著述を続けた。",
  },
  {
    id: "s-dalai-1",
    origin: "en",
    en: "Be kind whenever possible. It is always possible.",
    ja: "できる限り親切であれ。それは常に可能である。",
    kana: "できるかぎりしんせつであれ。それはつねにかのうである。",
    author: "ダライ・ラマ14世",
    authorEn: "Dalai Lama XIV",
    role: "チベット仏教の指導者",
    source: "ダライ・ラマ14世の言葉として広く伝わる",
    note: "「できる限り」と言いながら、それは常にできると言い切る構成が要点。状況を言い訳にせず親切を選べる、という励ましになっている。",
  },
  {
    id: "s-emerson-1",
    origin: "en",
    en: "Do not go where the path may lead, go instead where there is no path.",
    ja: "道のある所へ行くな。道なき所へ行き、跡を残せ。",
    kana: "みちのあるところへいくな。みちなきところへいき、あとをのこせ。",
    author: "エマーソン",
    authorEn: "Ralph Waldo Emerson",
    role: "思想家・詩人",
    source: "エマーソンの言葉として広く伝わる",
    note: "既にある道をたどるより、自分で道を作れという独立の勧め。エマーソンは個人が既存の権威に頼らず自立することを説いた。",
  },
  {
    id: "s-aristotle-3",
    origin: "en",
    en: "Well begun is half done.",
    ja: "よく始めることは、半ば成し遂げたことである。",
    kana: "よくはじめることは、なかばなしとげたことである。",
    author: "アリストテレス",
    authorEn: "Aristotle",
    role: "哲学者",
    source: "アリストテレスに帰される古代の格言",
    note: "出だしを丁寧にやれば仕事の半分は終わったも同然、という意味。段取りの重要さを説くことわざとして今も広く使われる。",
  },
  {
    id: "s-plato-1",
    origin: "en",
    en: "The beginning is the most important part of the work.",
    ja: "仕事において、始まりこそが最も重要な部分である。",
    kana: "しごとにおいて、はじまりこそがもっともじゅうようなぶぶんである。",
    author: "プラトン",
    authorEn: "Plato",
    role: "哲学者",
    source: "『国家』第2巻",
    note: "教育について論じる文脈で、幼少期に何を与えるかが人を形づくると述べた一節。最初の方向づけが後々まで効くという考え。",
  },
  {
    id: "s-edison-3",
    origin: "en",
    en: "Our greatest weakness lies in giving up.",
    ja: "最大の弱点は、諦めることにある。",
    kana: "さいだいのじゃくてんは、あきらめることにある。",
    author: "トーマス・エジソン",
    authorEn: "Thomas Edison",
    role: "発明家",
    source: "エジソンの言葉として広く伝わる",
    note: "続けて「最も確実な成功法は、もう一度試すことだ」と語られる。膨大な失敗を前提に発明を進めた本人らしい言葉。",
  },
  {
    id: "s-jobs-1",
    origin: "en",
    en: "Stay hungry, stay foolish.",
    ja: "ハングリーであれ、愚か者であれ。",
    kana: "はんぐりーであれ、おろかものであれ。",
    author: "スティーブ・ジョブズ",
    authorEn: "Steve Jobs",
    role: "実業家",
    source: "スタンフォード大学卒業式スピーチ(2005)",
    note: "満足せず、常識にとらわれるなという呼びかけ。ジョブズが若い頃に愛読した雑誌『全地球カタログ』最終号の裏表紙にあった言葉を引用したもの。",
  },
  {
    id: "s-jobs-2",
    origin: "en",
    en: "Your time is limited, so don't waste it living someone else's life.",
    ja: "時間は限られている。他人の人生を生きて無駄にするな。",
    kana: "じかんはかぎられている。たにんのじんせいをいきてむだにするな。",
    author: "スティーブ・ジョブズ",
    authorEn: "Steve Jobs",
    role: "実業家",
    source: "スタンフォード大学卒業式スピーチ(2005)",
    note: "がんの診断を受けた経験を語ったうえで述べられた一節。死を意識することが、本当にやりたいことを選ぶ助けになると説いた。",
  },
  {
    id: "s-drucker-1",
    origin: "en",
    en: "The best way to predict the future is to create it.",
    ja: "未来を予測する最良の方法は、それを創ることだ。",
    kana: "みらいをよそくするさいりょうのほうほうは、それをつくることだ。",
    author: "ピーター・ドラッカー",
    authorEn: "Peter Drucker",
    role: "経営学者",
    source: "ドラッカーの言葉として広く伝わる",
    note: "予測に頭を使うより、自分で作ってしまえという発想の転換。経営における主体性を説く文脈で引かれることが多い。",
  },
  {
    id: "s-hellen-3",
    origin: "en",
    en: "Life is either a daring adventure or nothing.",
    ja: "人生とは、大胆な冒険か、さもなくば無である。",
    kana: "じんせいとは、だいたんなぼうけんか、さもなくばむである。",
    author: "ヘレン・ケラー",
    authorEn: "Helen Keller",
    role: "教育者・社会福祉活動家",
    source: "『私の生涯』ほか著述に伝わる",
    note: "安全に閉じこもるだけでは生きているとは言えないという主張。重い障害を負いながら世界各地を講演して回った本人の生き方そのもの。",
  },
  {
    id: "s-confucius-4",
    origin: "ja",
    en: "When you make a mistake, do not be afraid to correct it.",
    ja: "過ちて改めざる、これを過ちという。",
    kana: "あやまちてあらためざる、これをあやまちという。",
    author: "孔子",
    authorEn: "Confucius",
    role: "思想家",
    source: "『論語』衛霊公篇",
    note: "間違えること自体ではなく、直さないことが本当の過ちだという教え。失敗を認めて改める姿勢を重んじた孔子の考えを端的に示す。",
  },
  {
    id: "s-basho-2",
    origin: "ja",
    en: "An old pond; a frog jumps in, the sound of water.",
    ja: "古池や蛙飛びこむ水の音。",
    kana: "ふるいけやかわずとびこむみずのおと。",
    author: "松尾芭蕉",
    authorEn: "Matsuo Basho",
    role: "俳人",
    source: "『蛙合』(1686)",
    note: "日本で最も知られた俳句。静けさの中に一瞬の音が響き、その後にまた静寂が戻る。動きと静けさを17音で表現した芭蕉の代表作。",
  },
  {
    id: "s-takuboku-1",
    origin: "ja",
    en: "Work, and still my life grows no easier; I stare at my hands.",
    ja: "はたらけどはたらけど猶わが生活楽にならざりぢっと手を見る。",
    kana: "はたらけどはたらけどなおわがくらしらくにならざりぢっとてをみる。",
    author: "石川啄木",
    authorEn: "Takuboku Ishikawa",
    role: "歌人",
    source: "『一握の砂』(1910)",
    note: "働いても暮らしが楽にならない生活の実感を詠んだ歌。啄木は貧困と病に苦しみ26歳で亡くなったが、この率直さが今も読み継がれている。",
  },
  {
    id: "s-sen-2",
    origin: "ja",
    en: "In the way of tea, harmony, respect, purity, and tranquility.",
    ja: "和敬清寂、茶の心はこの四字に尽きる。",
    kana: "わけいせいじゃく、ちゃのこころはこのよじにつきる。",
    author: "千利休",
    authorEn: "Sen no Rikyu",
    role: "茶人",
    source: "利休が示した茶道の四規として伝わる",
    note: "和(調和)・敬(敬意)・清(清らかさ)・寂(静けさ)の四つ。豪華さを競う茶から、簡素さの中に美を見出す侘び茶へ転換させた利休の理念。",
  },
  {
    id: "s-newton-2",
    origin: "en",
    en: "What we know is a drop, what we don't know is an ocean.",
    ja: "我々が知ることは一滴、知らないことは大海である。",
    kana: "われわれがしることはいってき、しらないことはたいかいである。",
    author: "アイザック・ニュートン",
    authorEn: "Isaac Newton",
    role: "物理学者・数学者",
    source: "ニュートンの言葉として広く伝わる",
    note: "自らを、真理の大海を前に浜辺で貝殻を拾う子どものようだと語ったという逸話に基づく。近代科学を築いた人物の謙虚さを示す言葉。",
  },
  {
    id: "s-anne-1",
    origin: "en",
    en: "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
    ja: "世界を良くするのに、一瞬たりとも待つ必要がないのは素晴らしい。",
    kana: "せかいをよくするのに、いっしゅんたりともまつひつようがないのはすばらしい。",
    author: "アンネ・フランク",
    authorEn: "Anne Frank",
    role: "『アンネの日記』の著者",
    source: "『アンネの日記』1944年3月26日",
    note: "隠れ家での生活が2年近くに及んだ時期に書かれた一節。自由を奪われた状況でも、今この場からできることがあると記した。",
  },
];
