import type { Quote } from "../types";

/** 政治・社会・リーダーシップ */
export const SOCIETY: Quote[] = [
  {
    id: "lincoln-1",
    origin: "en",
    en: "Whatever you are, be a good one.",
    ja: "何になるにしても、良いものになりなさい。",
    kana: "なにになるにしても、よいものになりなさい。",
    author: "エイブラハム・リンカーン",
    authorEn: "Abraham Lincoln",
    role: "アメリカ大統領",
    source: "リンカーンの言葉として広く伝わる",
    note: "職業や立場そのものより、それをどこまで真剣にやるかが人の価値を決めるという意味。丸太小屋育ちから大統領になった本人の歩みと重ねて語られることが多い。",
  },
  {
    id: "lincoln-2",
    origin: "en",
    en: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.",
    ja: "逆境に耐えられる者は多い。人の本性を試したければ、権力を与えてみよ。",
    kana: "ぎゃっきょうにたえられるものはおおい。ひとのほんしょうをためしたければ、けんりょくをあたえてみよ。",
    author: "エイブラハム・リンカーン",
    authorEn: "Abraham Lincoln",
    role: "アメリカ大統領",
    source: "リンカーンの言葉として広く伝わる",
    note: "苦境では我慢できても、力を持ったときにどう振る舞うかにその人の地金が出るという洞察。南北戦争という強大な権限を握った時期を生きた人の言葉。",
  },
  {
    id: "lincoln-3",
    origin: "en",
    en: "Government of the people, by the people, for the people.",
    ja: "人民の、人民による、人民のための政治。",
    kana: "じんみんの、じんみんによる、じんみんのためのせいじ。",
    author: "エイブラハム・リンカーン",
    authorEn: "Abraham Lincoln",
    role: "アメリカ大統領",
    source: "ゲティスバーグ演説(1863年11月19日)",
    note: "民主主義を三つの前置詞で言い表した一節。激戦地の戦没者墓地の奉献式で、わずか2分ほどの演説の結びとして語られた。",
  },
  {
    id: "gandhi-1",
    origin: "en",
    en: "The best way to find yourself is to lose yourself in the service of others.",
    ja: "自分を見つける最良の道は、他者への奉仕に自分を忘れることだ。",
    kana: "じぶんをみつけるさいりょうのみちは、たしゃへのほうしにじぶんをわすれることだ。",
    author: "マハトマ・ガンジー",
    authorEn: "Mahatma Gandhi",
    role: "宗教家・政治指導者",
    source: "ガンジーの著述に伝わる言葉",
    note: "自分探しは内へこもるより、人のために動く中でこそ見つかるという逆説。インド独立運動を非暴力で率いた本人の実践がこの言葉を支えている。",
  },
  {
    id: "mandela-1",
    origin: "en",
    en: "It always seems impossible until it's done.",
    ja: "何事も成し遂げるまでは、不可能に思えるものだ。",
    kana: "なにごともなしとげるまでは、ふかのうにおもえるものだ。",
    author: "ネルソン・マンデラ",
    authorEn: "Nelson Mandela",
    role: "南アフリカ大統領",
    source: "マンデラの演説・著述に伝わる",
    note: "実現してしまえば当たり前に見えることも、その前は誰もが無理だと思っていた、という意味。27年の投獄を経てアパルトヘイトを終わらせた人の実感がこもる。",
  },
  {
    id: "mandela-2",
    origin: "en",
    en: "Education is the most powerful weapon which you can use to change the world.",
    ja: "教育こそが、世界を変えるために使える最も強力な武器である。",
    kana: "きょういくこそが、せかいをかえるためにつかえるもっともきょうりょくなぶきである。",
    author: "ネルソン・マンデラ",
    authorEn: "Nelson Mandela",
    role: "南アフリカ大統領",
    source: "1990年代の演説として伝わる",
    note: "暴力ではなく教育が社会を変えるという信念。マンデラ自身、獄中でも学び続け、出所後は教育機会の拡大を国づくりの柱に据えた。",
  },
  {
    id: "king-1",
    origin: "en",
    en: "Faith is taking the first step even when you don't see the whole staircase.",
    ja: "信念とは、階段の全体が見えなくとも最初の一歩を踏み出すことだ。",
    kana: "しんねんとは、かいだんのぜんたいがみえなくともさいしょのいっぽをふみだすことだ。",
    author: "キング牧師",
    authorEn: "Martin Luther King Jr.",
    role: "公民権運動指導者",
    source: "キング牧師の説教に伝わる言葉",
    note: "先が見通せないからこそ、踏み出すことが信念だという意味。公民権運動は成功の保証がないまま始まった行動の連続だった。",
  },
  {
    id: "king-2",
    origin: "en",
    en: "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin.",
    ja: "私には夢がある。いつか子どもたちが肌の色で判断されない国に生きるという夢が。",
    kana: "わたしにはゆめがある。いつかこどもたちがはだのいろではんだんされないくににいきるというゆめが。",
    author: "キング牧師",
    authorEn: "Martin Luther King Jr.",
    role: "公民権運動指導者",
    source: "ワシントン大行進での演説(1963年8月28日)",
    note: "20万人以上を前にした演説の中心部分。原稿にはなく、歌手マヘリア・ジャクソンの「夢について話して」という声を受けて即興で語られたと言われる。",
  },
  {
    id: "churchill-1",
    origin: "en",
    en: "Never, never, never give in.",
    ja: "決して、決して、決して屈するな。",
    kana: "けっして、けっして、けっしてくっするな。",
    author: "ウィンストン・チャーチル",
    authorEn: "Winston Churchill",
    role: "イギリス首相",
    source: "ハロー校での演説(1941年10月29日)",
    note: "第二次大戦の最も苦しい時期に母校の生徒へ語った言葉。同じ語を三度繰り返すことで、理屈ではなく意志として聴衆に刻み込んだ。",
  },
  {
    id: "roosevelt-1",
    origin: "en",
    en: "The only thing we have to fear is fear itself.",
    ja: "我々が恐れるべき唯一のものは、恐れそのものである。",
    kana: "われわれがおそれるべきゆいいつのものは、おそれそのものである。",
    author: "フランクリン・ルーズベルト",
    authorEn: "Franklin D. Roosevelt",
    role: "アメリカ大統領",
    source: "第1回大統領就任演説(1933年3月4日)",
    note: "世界恐慌のさなかの就任演説。銀行の取り付け騒ぎのように、恐怖そのものが事態を悪化させていた状況で、まず国民の心理を立て直そうとした一文。",
  },
  {
    id: "eroosevelt-1",
    origin: "en",
    en: "The future belongs to those who believe in the beauty of their dreams.",
    ja: "未来は、自分の夢の美しさを信じる人のものである。",
    kana: "みらいは、じぶんのゆめのうつくしさをしんじるひとのものである。",
    author: "エレノア・ルーズベルト",
    authorEn: "Eleanor Roosevelt",
    role: "人権活動家",
    source: "エレノアの言葉として広く伝わる",
    note: "夢を信じ続けられるかどうかが未来を分けるという意味。世界人権宣言の起草を主導し、理想を文書として形にした人物の言葉として語り継がれている。",
  },
  {
    id: "eroosevelt-2",
    origin: "en",
    en: "No one can make you feel inferior without your consent.",
    ja: "あなたの同意なしに、誰もあなたを劣った気持ちにはできない。",
    kana: "あなたのどういなしに、だれもあなたをおとったきもちにはできない。",
    author: "エレノア・ルーズベルト",
    authorEn: "Eleanor Roosevelt",
    role: "人権活動家",
    source: "エレノアの言葉として広く伝わる",
    note: "他人の評価を受け入れるかどうかは自分が決められる、という意味。人前に出ることを苦手としながら公の場で発言し続けた本人の経験が背景にある。",
  },
  {
    id: "kennedy-1",
    origin: "en",
    en: "Ask not what your country can do for you, ask what you can do for your country.",
    ja: "国が何をしてくれるかではなく、自分が国に何をできるかを問え。",
    kana: "くにがなにをしてくれるかではなく、じぶんがくにになにをできるかをとえ。",
    author: "ジョン・F・ケネディ",
    authorEn: "John F. Kennedy",
    role: "アメリカ大統領",
    source: "大統領就任演説(1961年1月20日)",
    note: "受け取る側から担う側へ意識を切り替えるよう促した一節。この呼びかけが平和部隊(ピースコー)創設など、市民参加の動きにつながった。",
  },
  {
    id: "teresa-1",
    origin: "en",
    en: "If you can't feed a hundred people, then feed just one.",
    ja: "百人を助けられないなら、まず一人を助けなさい。",
    kana: "ひゃくにんをたすけられないなら、まずひとりをたすけなさい。",
    author: "マザー・テレサ",
    authorEn: "Mother Teresa",
    role: "修道女",
    source: "マザー・テレサの言葉として広く伝わる",
    note: "問題の大きさに圧倒されて何もしないより、目の前の一人に手を差し伸べよという教え。カルカッタでの活動は、路上に倒れた一人を看取ることから始まった。",
  },
  {
    id: "teresa-2",
    origin: "en",
    en: "Peace begins with a smile.",
    ja: "平和は、微笑みから始まる。",
    kana: "へいわは、ほほえみからはじまる。",
    author: "マザー・テレサ",
    authorEn: "Mother Teresa",
    role: "修道女",
    source: "マザー・テレサの言葉として広く伝わる",
    note: "大きな理念ではなく、日常のささやかな態度こそが平和の出発点だという考え。誰にでも今すぐできることとして語られた。",
  },
  {
    id: "keller-1",
    origin: "en",
    en: "Alone we can do so little; together we can do so much.",
    ja: "一人でできることは少ない。しかし共になせば多くを成せる。",
    kana: "ひとりでできることはすくない。しかしともになせばおおくをなせる。",
    author: "ヘレン・ケラー",
    authorEn: "Helen Keller",
    role: "教育者・社会福祉活動家",
    source: "ヘレン・ケラーの著述に伝わる",
    note: "視覚と聴覚を失いながら、家庭教師サリヴァンをはじめ多くの人の支えで世界に働きかけた本人の実感。協力の力を端的に言い表している。",
  },
  {
    id: "keller-2",
    origin: "en",
    en: "Optimism is the faith that leads to achievement.",
    ja: "楽観こそが、達成へと導く信念である。",
    kana: "らっかんこそが、たっせいへとみちびくしんねんである。",
    author: "ヘレン・ケラー",
    authorEn: "Helen Keller",
    role: "教育者・社会福祉活動家",
    source: "『楽天主義』(1903)",
    note: "楽観は現実から目をそらすことではなく、行動を起こさせる力だという主張。ハーバード大学在学中に書いたエッセイの一節。",
  },
  {
    id: "nightingale-2",
    origin: "en",
    en: "How very little can be done under the spirit of fear.",
    ja: "恐れの気持ちのもとでは、ほとんど何もできない。",
    kana: "おそれのきもちのもとでは、ほとんどなにもできない。",
    author: "フローレンス・ナイチンゲール",
    authorEn: "Florence Nightingale",
    role: "看護師・統計学者",
    source: "ナイチンゲールの書簡に伝わる",
    note: "萎縮した状態では判断も行動も鈍るという指摘。軍上層部の反対を押し切って病院の改革を進めた経験から出た言葉とされる。",
  },
];
