import type { Quote } from "./types";

/**
 * 偉人の名言リスト。
 *
 * - `origin` はその名言がもともと何語で語られたかを表す。
 *   欧米の偉人は英語(や英訳が定着したもの)が原文、日本の偉人は日本語が原文。
 * - `kana` は日本語モードのローマ字判定に使う読み。表示は `ja` の漢字かな交じり文、
 *   打鍵の判定は `kana` を romaji.ts でローマ字に展開して行う。
 * - 「狂気とは同じことを繰り返し、違う結果を期待することだ」(アインシュタイン)のように
 *   広く誤って帰属されている言葉は、出典が確認できないため意図的に除いてある。
 */
export const QUOTES: Quote[] = [
  // ===== 発明・科学 =====
  {
    id: "edison-1",
    origin: "en",
    en: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    ja: "天才とは、一％のひらめきと九十九％の汗である。",
    kana: "てんさいとは、いちぱーせんとのひらめきときゅうじゅうきゅうぱーせんとのあせである。",
    author: "トーマス・エジソン",
    authorEn: "Thomas Edison",
    role: "発明家",
  },
  {
    id: "edison-2",
    origin: "en",
    en: "I have not failed. I've just found ten thousand ways that won't work.",
    ja: "私は失敗していない。うまくいかない方法を一万通り見つけただけだ。",
    kana: "わたしはしっぱいしていない。うまくいかないほうほうをいちまんとおりみつけただけだ。",
    author: "トーマス・エジソン",
    authorEn: "Thomas Edison",
    role: "発明家",
  },
  {
    id: "einstein-1",
    origin: "en",
    en: "Imagination is more important than knowledge.",
    ja: "想像力は知識よりも大切である。",
    kana: "そうぞうりょくはちしきよりもたいせつである。",
    author: "アルベルト・アインシュタイン",
    authorEn: "Albert Einstein",
    role: "物理学者",
  },
  {
    id: "einstein-2",
    origin: "en",
    en: "Try not to become a man of success, but rather try to become a man of value.",
    ja: "成功者になろうとするな。むしろ価値のある人間になろうとせよ。",
    kana: "せいこうしゃになろうとするな。むしろかちのあるにんげんになろうとせよ。",
    author: "アルベルト・アインシュタイン",
    authorEn: "Albert Einstein",
    role: "物理学者",
  },
  {
    id: "curie-1",
    origin: "en",
    en: "Nothing in life is to be feared, it is only to be understood.",
    ja: "人生において恐れるべきものは何もない。ただ理解すべきものがあるだけだ。",
    kana: "じんせいにおいておそれるべきものはなにもない。ただりかいすべきものがあるだけだ。",
    author: "マリー・キュリー",
    authorEn: "Marie Curie",
    role: "物理学者・化学者",
  },
  {
    id: "newton-1",
    origin: "en",
    en: "If I have seen further, it is by standing on the shoulders of giants.",
    ja: "私が遠くを見渡せたのは、巨人の肩の上に立っていたからだ。",
    kana: "わたしがとおくをみわたせたのは、きょじんのかたのうえにたっていたからだ。",
    author: "アイザック・ニュートン",
    authorEn: "Isaac Newton",
    role: "物理学者・数学者",
  },
  {
    id: "darwin-1",
    origin: "en",
    en: "It is not the strongest of the species that survives, but the most adaptable.",
    ja: "生き残るのは最も強い種ではなく、最も変化に適応した種である。",
    kana: "いきのこるのはもっともつよいしゅではなく、もっともへんかにてきおうしたしゅである。",
    author: "チャールズ・ダーウィン",
    authorEn: "Charles Darwin",
    role: "自然科学者",
  },

  // ===== 哲学・思想 =====
  {
    id: "socrates-1",
    origin: "en",
    en: "The unexamined life is not worth living.",
    ja: "吟味されざる生に、生きる値打ちなし。",
    kana: "ぎんみされざるせいに、いきるねうちなし。",
    author: "ソクラテス",
    authorEn: "Socrates",
    role: "哲学者",
  },
  {
    id: "aristotle-1",
    origin: "en",
    en: "We are what we repeatedly do. Excellence, then, is not an act but a habit.",
    ja: "人は繰り返す行いそのものである。ゆえに卓越とは行為ではなく習慣である。",
    kana: "ひとはくりかえすおこないそのものである。ゆえにたくえつとはこういではなくしゅうかんである。",
    author: "アリストテレス",
    authorEn: "Aristotle",
    role: "哲学者",
  },
  {
    id: "confucius-1",
    origin: "ja",
    en: "To know what you know and to know what you do not know: that is knowledge.",
    ja: "知るを知るとなし、知らざるを知らずとなす。これ知るなり。",
    kana: "しるをしるとなし、しらざるをしらずとなす。これしるなり。",
    author: "孔子",
    authorEn: "Confucius",
    role: "思想家",
  },
  {
    id: "confucius-2",
    origin: "ja",
    en: "It does not matter how slowly you go so long as you do not stop.",
    ja: "どんなに遅くとも、歩みを止めさえしなければよい。",
    kana: "どんなにおそくとも、あゆみをとめさえしなければよい。",
    author: "孔子",
    authorEn: "Confucius",
    role: "思想家",
  },
  {
    id: "seneca-1",
    origin: "en",
    en: "It is not that we have a short time to live, but that we waste a lot of it.",
    ja: "人生が短いのではない。我々がそれを浪費しているのだ。",
    kana: "じんせいがみじかいのではない。われわれがそれをろうひしているのだ。",
    author: "セネカ",
    authorEn: "Seneca",
    role: "哲学者",
  },
  {
    id: "goethe-1",
    origin: "en",
    en: "Whatever you can do or dream you can, begin it. Boldness has genius in it.",
    ja: "できること、夢見ることがあるなら始めよ。大胆さの中には才能が宿る。",
    kana: "できること、ゆめみることがあるならはじめよ。だいたんさのなかにはさいのうがやどる。",
    author: "ゲーテ",
    authorEn: "Johann Wolfgang von Goethe",
    role: "詩人・作家",
  },
  {
    id: "nietzsche-1",
    origin: "en",
    en: "He who has a why to live can bear almost any how.",
    ja: "なぜ生きるかを知る者は、ほとんどあらゆる生き方に耐える。",
    kana: "なぜいきるかをしるものは、ほとんどあらゆるいきかたにたえる。",
    author: "ニーチェ",
    authorEn: "Friedrich Nietzsche",
    role: "哲学者",
  },

  // ===== 政治・社会 =====
  {
    id: "lincoln-1",
    origin: "en",
    en: "Whatever you are, be a good one.",
    ja: "何になるにしても、良いものになりなさい。",
    kana: "なにになるにしても、よいものになりなさい。",
    author: "エイブラハム・リンカーン",
    authorEn: "Abraham Lincoln",
    role: "アメリカ大統領",
  },
  {
    id: "lincoln-2",
    origin: "en",
    en: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.",
    ja: "逆境に耐えられる者は多い。人の本性を試したければ、権力を与えてみよ。",
    kana: "ぎゃっきょうにたえられるものはおおい。ひとのほんしょうをためしたければ、けんりょくをあたえてみよ。",
    author: "エイブラハム・リンカーン",
    authorEn: "Abraham Lincoln",
    role: "アメリカ大統領",
  },
  {
    id: "gandhi-1",
    origin: "en",
    en: "The best way to find yourself is to lose yourself in the service of others.",
    ja: "自分を見つける最良の道は、他者への奉仕に自分を忘れることだ。",
    kana: "じぶんをみつけるさいりょうのみちは、たしゃへのほうしにじぶんをわすれることだ。",
    author: "マハトマ・ガンジー",
    authorEn: "Mahatma Gandhi",
    role: "宗教家・政治指導者",
  },
  {
    id: "mandela-1",
    origin: "en",
    en: "It always seems impossible until it's done.",
    ja: "何事も成し遂げるまでは、不可能に思えるものだ。",
    kana: "なにごともなしとげるまでは、ふかのうにおもえるものだ。",
    author: "ネルソン・マンデラ",
    authorEn: "Nelson Mandela",
    role: "南アフリカ大統領",
  },
  {
    id: "king-1",
    origin: "en",
    en: "Faith is taking the first step even when you don't see the whole staircase.",
    ja: "信念とは、階段の全体が見えなくとも最初の一歩を踏み出すことだ。",
    kana: "しんねんとは、かいだんのぜんたいがみえなくともさいしょのいっぽをふみだすことだ。",
    author: "キング牧師",
    authorEn: "Martin Luther King Jr.",
    role: "公民権運動指導者",
  },
  {
    id: "churchill-1",
    origin: "en",
    en: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    ja: "成功は終わりではなく、失敗は致命的ではない。大切なのは続ける勇気だ。",
    kana: "せいこうはおわりではなく、しっぱいはちめいてきではない。たいせつなのはつづけるゆうきだ。",
    author: "ウィンストン・チャーチル",
    authorEn: "Winston Churchill",
    role: "イギリス首相",
  },
  {
    id: "roosevelt-1",
    origin: "en",
    en: "The only thing we have to fear is fear itself.",
    ja: "我々が恐れるべき唯一のものは、恐れそのものである。",
    kana: "われわれがおそれるべきゆいいつのものは、おそれそのものである。",
    author: "フランクリン・ルーズベルト",
    authorEn: "Franklin D. Roosevelt",
    role: "アメリカ大統領",
  },
  {
    id: "eroosevelt-1",
    origin: "en",
    en: "The future belongs to those who believe in the beauty of their dreams.",
    ja: "未来は、自分の夢の美しさを信じる人のものである。",
    kana: "みらいは、じぶんのゆめのうつくしさをしんじるひとのものである。",
    author: "エレノア・ルーズベルト",
    authorEn: "Eleanor Roosevelt",
    role: "人権活動家",
  },

  // ===== 芸術・文学 =====
  {
    id: "shakespeare-1",
    origin: "en",
    en: "All the world's a stage, and all the men and women merely players.",
    ja: "この世は舞台、人はみな役者にすぎない。",
    kana: "このよはぶたい、ひとはみなやくしゃにすぎない。",
    author: "シェイクスピア",
    authorEn: "William Shakespeare",
    role: "劇作家",
  },
  {
    id: "picasso-1",
    origin: "en",
    en: "Every child is an artist. The problem is how to remain an artist once we grow up.",
    ja: "子どもはみな芸術家だ。問題は大人になっても芸術家でいられるかだ。",
    kana: "こどもはみなげいじゅつかだ。もんだいはおとなになってもげいじゅつかでいられるかだ。",
    author: "パブロ・ピカソ",
    authorEn: "Pablo Picasso",
    role: "画家",
  },
  {
    id: "vangogh-1",
    origin: "en",
    en: "Great things are not done by impulse, but by a series of small things brought together.",
    ja: "偉大なことは衝動ではなく、小さなことの積み重ねで成し遂げられる。",
    kana: "いだいなことはしょうどうではなく、ちいさなことのつみかさねでなしとげられる。",
    author: "ゴッホ",
    authorEn: "Vincent van Gogh",
    role: "画家",
  },
  {
    id: "davinci-1",
    origin: "en",
    en: "Simplicity is the ultimate sophistication.",
    ja: "単純さこそ、究極の洗練である。",
    kana: "たんじゅんさこそ、きゅうきょくのせんれんである。",
    author: "レオナルド・ダ・ヴィンチ",
    authorEn: "Leonardo da Vinci",
    role: "芸術家・科学者",
  },
  {
    id: "beethoven-1",
    origin: "en",
    en: "Music is a higher revelation than all wisdom and philosophy.",
    ja: "音楽は、あらゆる知恵や哲学よりも高き啓示である。",
    kana: "おんがくは、あらゆるちえやてつがくよりもたかきけいじである。",
    author: "ベートーヴェン",
    authorEn: "Ludwig van Beethoven",
    role: "作曲家",
  },

  // ===== 逆境・挑戦 =====
  {
    id: "keller-1",
    origin: "en",
    en: "Alone we can do so little; together we can do so much.",
    ja: "一人でできることは少ない。しかし共になせば多くを成せる。",
    kana: "ひとりでできることはすくない。しかしともになせばおおくをなせる。",
    author: "ヘレン・ケラー",
    authorEn: "Helen Keller",
    role: "教育者・社会福祉活動家",
  },
  {
    id: "keller-2",
    origin: "en",
    en: "Optimism is the faith that leads to achievement.",
    ja: "楽観こそが、達成へと導く信念である。",
    kana: "らっかんこそが、たっせいへとみちびくしんねんである。",
    author: "ヘレン・ケラー",
    authorEn: "Helen Keller",
    role: "教育者・社会福祉活動家",
  },
  {
    id: "nightingale-1",
    origin: "en",
    en: "I attribute my success to this: I never gave or took any excuse.",
    ja: "私の成功の理由はこれだ。言い訳をせず、言い訳を受け入れもしなかった。",
    kana: "わたしのせいこうのりゆうはこれだ。いいわけをせず、いいわけをうけいれもしなかった。",
    author: "フローレンス・ナイチンゲール",
    authorEn: "Florence Nightingale",
    role: "看護師・統計学者",
  },
  {
    id: "franklin-1",
    origin: "en",
    en: "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    ja: "言われたことは忘れる。教わったことは覚える。関われば身につく。",
    kana: "いわれたことはわすれる。おそわったことはおぼえる。かかわればみにつく。",
    author: "ベンジャミン・フランクリン",
    authorEn: "Benjamin Franklin",
    role: "政治家・科学者",
  },
  {
    id: "twain-1",
    origin: "en",
    en: "The secret of getting ahead is getting started.",
    ja: "前へ進む秘訣は、まず始めることである。",
    kana: "まえへすすむひけつは、まずはじめることである。",
    author: "マーク・トウェイン",
    authorEn: "Mark Twain",
    role: "作家",
  },

  // ===== 日本の偉人 =====
  {
    id: "fukuzawa-1",
    origin: "ja",
    en: "Heaven creates no man above another, nor any man below another.",
    ja: "天は人の上に人を造らず、人の下に人を造らず。",
    kana: "てんはひとのうえにひとをつくらず、ひとのしたにひとをつくらず。",
    author: "福沢諭吉",
    authorEn: "Yukichi Fukuzawa",
    role: "思想家・教育者",
  },
  {
    id: "noguchi-1",
    origin: "ja",
    en: "I was not born into this world in vain.",
    ja: "私は無駄にこの世に生まれてきたのではない。",
    kana: "わたしはむだにこのよにうまれてきたのではない。",
    author: "野口英世",
    authorEn: "Hideyo Noguchi",
    role: "細菌学者",
  },
  {
    id: "matsushita-1",
    origin: "ja",
    en: "When you hit a wall, the first thing to change is your own point of view.",
    ja: "何事もゆきづまれば、まず自分のものの見方を変えることである。",
    kana: "なにごともゆきづまれば、まずじぶんのもののみかたをかえることである。",
    author: "松下幸之助",
    authorEn: "Konosuke Matsushita",
    role: "実業家",
  },
  {
    id: "ryoma-1",
    origin: "ja",
    en: "A man should do what he alone can do in this life.",
    ja: "世の中の人は何とも言わば言え。我が成すことは我のみぞ知る。",
    kana: "よのなかのひとはなんともいわばいえ。わがなすことはわれのみぞしる。",
    author: "坂本龍馬",
    authorEn: "Ryoma Sakamoto",
    role: "幕末の志士",
  },
  {
    id: "yoshida-1",
    origin: "ja",
    en: "Where there is sincerity, there is nothing that cannot move a person.",
    ja: "誠の心があれば、動かせぬものは何もない。",
    kana: "まことのこころがあれば、うごかせぬものはなにもない。",
    author: "吉田松陰",
    authorEn: "Shoin Yoshida",
    role: "思想家・教育者",
  },
  {
    id: "shibusawa-1",
    origin: "ja",
    en: "An abacus without a moral compass, and morals without an abacus, both fail.",
    ja: "論語と算盤、どちらを欠いても正しい商いは成り立たない。",
    kana: "ろんごとそろばん、どちらをかいてもただしいあきないはなりたたない。",
    author: "渋沢栄一",
    authorEn: "Eiichi Shibusawa",
    role: "実業家",
  },
  {
    id: "hideyoshi-1",
    origin: "ja",
    en: "If a man does not act, nothing in this world will come to pass.",
    ja: "自ら動かねば、この世に成ることは何一つない。",
    kana: "みずからうごかねば、このよになることはなにひとつない。",
    author: "豊臣秀吉",
    authorEn: "Hideyoshi Toyotomi",
    role: "戦国武将",
  },
  {
    id: "ieyasu-1",
    origin: "ja",
    en: "Life is like walking a long road with a heavy burden; do not be in a hurry.",
    ja: "人の一生は重荷を負うて遠き道を行くがごとし。急ぐべからず。",
    kana: "ひとのいっしょうはおもにをおうてとおきみちをゆくがごとし。いそぐべからず。",
    author: "徳川家康",
    authorEn: "Ieyasu Tokugawa",
    role: "武将・征夷大将軍",
  },
  {
    id: "murasaki-1",
    origin: "ja",
    en: "People's hearts are as varied as their faces.",
    ja: "人の心は顔かたちと同じく、それぞれに異なるものだ。",
    kana: "ひとのこころはかおかたちとおなじく、それぞれにことなるものだ。",
    author: "紫式部",
    authorEn: "Murasaki Shikibu",
    role: "作家・歌人",
  },
  {
    id: "basho-1",
    origin: "ja",
    en: "Do not follow in the footsteps of the old masters; seek what they sought.",
    ja: "古人の跡を求めず、古人の求めたる所を求めよ。",
    kana: "こじんのあとをもとめず、こじんのもとめたるところをもとめよ。",
    author: "松尾芭蕉",
    authorEn: "Matsuo Basho",
    role: "俳人",
  },
  {
    id: "tsuda-1",
    origin: "ja",
    en: "What matters is not knowledge itself, but the character that puts it to use.",
    ja: "大切なのは知識そのものではなく、それを生かす人格である。",
    kana: "たいせつなのはちしきそのものではなく、それをいかすじんかくである。",
    author: "津田梅子",
    authorEn: "Umeko Tsuda",
    role: "教育者",
  },
];
